import {
    Any,
    ArrayContainedBy,
    ArrayContains,
    In,
    LessThan,
    MoreThan,
    Not,
    Raw,
    IsNull,
    Like,
    MoreThanOrEqual,
    LessThanOrEqual,
    Between,
    ILike,
    ArrayOverlap,
} from 'typeorm';

export const FILTER_MAPPER ={
    not: Not,
    in: In,
    like: Like,
    more_than: MoreThan,
    less_than: LessThan,
    more_than_or_equal: MoreThanOrEqual,
    less_than_or_equal: LessThanOrEqual,
    between: Between,
    i_like:ILike,
    is_null: IsNull,
    raw: Raw,
    any: Any,
    array_contained_by: ArrayContainedBy,
    array_contains: ArrayContains,
    array_overlap: ArrayOverlap,
}